InsertGain = 0.320;
BackGroundGain = 0.390;
TestWrongIndexPersent_3Area = 20;
TestWrongIndexPersent_5Area = 10;
EnableReprint = true;
EnableAP = true;
EnableESPNOW = true;
Mode = HOST;
#模式是HOST或者SLAVE，SLAVE下ESP会尝试连接NetSSID的WiFi然后连接服务器
SSID = "魔法哔哔机";
Password = "";
NetSSID = "HOMOHOMO";
NetPassword = "12345678";
HostMAC = "";
BacklightTime = 30;
EspNowChannel = 1;
BackLight = 0.800;
