#插入的哔哔声音的音量
InsertGain = 0.40;

#背景的声音的音量
BackGroundGain = 0.40;

#错误字体出现概率：百分之
TestWrongIndexPersent_3Area = 15;
TestWrongIndexPersent_5Area = 8;

#哔哔声概率
InsertSoundBaseProbability = 20;
InsertSoundIncreaseProbability = 3;

#是否允许回滚
EnableReprint = true;


#ESP-NOW开关
EnableESPNOW = true;

#工作模式：AP_Config | STA_Online | STA_Only
Mode = AP_Config;

#本机热点名字
SSID = "魔法哔哔机";

#本机热点密码
Password = "";

#联网WIFI名字
NetSSID = "热点名字";

#联网WIFI密码
NetPassword = "12345678";

#指令获取网站
Net = "http://115.190.145.254:8080/random";

#主机MAC过滤|一般情况留空
HostMAC = "";

#背光变暗时间：秒
BacklightTime = 30;

#背光关闭时间：秒
BacklightCloseTime = 15;

#背光关闭后休眠时间：分钟
SleepTime = 10;

#背光亮度
BackLight = 0.400;

# Text display frame interval (ms)
DisplayIntervalMs = 5;

#ESP_NOW信道，如果要更改请确保和主机一致//看能不能改成全频道广播然后ESPAP自己选择WIFI
EspNowChannel = 1;

